### ISSUE TITLE
Display Article preview data of pages into a RV housed inside a Fragment

### ISSUE THREAD

**Issue by dasBikash84** [dasBikash84/news_server_android_app#27]
### Implementation steps
- [x] Create a new branch for the task.
- [x] Define required layouts for the parent fragment of RV.
- [x] Implement the fragment.
- [x] Wire the fragment with NewspaperPerviewFragment.
- [x] Test.

**Comment by dasBikash84** [comment]
Fixed with commit # a5571879a3484db6a
