### ISSUE TITLE
Implement necessary classes for log in/sign up

### ISSUE THREAD

**Issue by dasBikash84** [dasBikash84/news_server_android_app#30]

**Comment by dasBikash84** [comment]
### Factors to consider

1. Sign up during app flow.
2. Sign in during app flow.
3. App launch with signed in user.
4. App launch without signed in user.
5. User settings data fetch from server.
6. User settings merge with app settings after sign in.
7. User settings with app settings  after sign up.
8. Coping up with user settings during app flow.
9. User settings update and save to server.
10. Sign in/Sign up launching.

**Comment by dasBikash84** [comment]
**Sign in/up initiation paths:**

- Click on sign in/up icon.
- User attempt to modify app settings. (Except fav page adding)

**Comment by dasBikash84** [comment]
**Settings data merge with app settings after sign in**

- For new user fav page list will be written to server along with default page group data settings.
- For old user current settings data will be replaced with server settings.

**Comment by dasBikash84** [comment]
**User settings update and save to server:**

- Old settings will be replaced with new settings.
- Update time ,user device name and user IP will be stored.

**Comment by dasBikash84** [comment]
**App launch:**

- At launch signed in status will be checked.
- No action for detached user.
- If signed in then update time will be checked and compared with 'local last update time'. In case of miss-match settings will be fetched and old settings data will be over-written. New update time will be stored on shared preferences.

**Comment by dasBikash84** [comment]
**Coping up with user settings during app flow:**

- Settings repository methods will have to be modified to apply user settings.

**Comment by dasBikash84** [comment]
### Tasks:
- [ ] **Write rule in real-time DB to facilitate settings update history saving.**
- [ ] **Rough implementation of Article view activity for fav page adding.**
- [ ] **Implement Favourite fragment.**
- [ ] **Implement swipe delete of favourite page. Will prompt for sign in if not.**
- [ ] **Implement sign in/up request handler.**
- [ ] **Implement 'if need to update user settings' action. (all user settings related data transaction will have to proceed through user_settings_repo in following user_settings_data_service)**
- [ ] **Implement settings fetch and save action.**
- [ ] **Implement More Fragment.**
- [ ] **Implement in-view update/insert of page group. Will force sign in to proceed. Also support swipe removal of entire group.**
- [ ] **Implement settings post action. Update time ,user device name and user IP have to be saved.**
- [ ] **Create separate fragment for newspaper/page settings change. It could be accessed from settings fragment and also by sign in button. Settings action will force sign in to proceed.**
- [ ] **Implement handler of sign up button press at signed in state.**
- [ ] **Implement Settings fragment.**
- [ ] **Change "Settings repository methods " to take user settings into consideration.**

**Comment by dasBikash84** [comment]
### Working on
_Rough implementation of Article view activity for favourite page adding:_
At this point a rudimentary implementation of article view (PageViewActivity) needed with functionality to add/remove pages as favourites. So will have to go by following steps:

- [ ] Create activity. It's view will hold an ViewPager inside of which article display has to be done. In the top bar of page need menu items for add/remove pages from favourite lists. 
- [ ] Link article preview with the activity.
