### ISSUE TITLE
Finalize PageGroups Fragment

### ISSUE THREAD

**Issue by dasBikash84** [dasBikash84/news_server_android_app#36]
### Tasks:

1. Modify and finalize Fragment layout

- [x] Modify Page-group view-holder layout
- [x] Add layout to house edit view

2. Edit code

- [x] Edit view-holder code to handle edit actions.
- [x] Implement 'edit view' code and store data on viewholder
- [x] For positive edit command, wire viewholder data with fragment and perform edit.

3. Test

**Comment by dasBikash84** [comment]
Fixed by # 03f6582925155
