### ISSUE TITLE
Update code to cope with settings data format change (addition of active flag on Newspaper and Page POJO) on firebase database(s)

### ISSUE THREAD

**Issue by dasBikash84** [dasBikash84/news_server_android_app#54]

**Comment by dasBikash84** [comment]
### Tasks:

- [ ] Update appSettingsDataservice for firebase-Db
- [ ] Update appSettingsDataservice for firestore-Db
- [ ] Update appSettingsDataservice for springMVCDataService
