### ISSUE TITLE
Implement article save and display

### ISSUE THREAD

**Issue by dasBikash84** [dasBikash84/news_server_android_app#55]
### Tasks:

- [x] Add new table to hold saved articles.

- [x] Implement code for article save and delete. And link that with view controller.

- [x] Implement saved article display.

**Comment by dasBikash84** [comment]
Fixed by # b70826acaf2.
